name: Simple Commit Check

on:
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR has exactly one conventional commit
        run: |
          # Count commits between base and head
          COMMITS=$(git log --oneline ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
          COMMIT_MSG=$(git log -1 --pretty=format:%s ${{ github.event.pull_request.head.sha }})
          
          echo "=== COMMIT VALIDATION ==="
          echo "Commit count: $COMMIT_COUNT"
          echo "Commit message: $COMMIT_MSG"
          echo "========================="
          
          # Check single commit
          if [ "$COMMIT_COUNT" -ne 1 ]; then
            echo "❌ FAIL: PR must have exactly 1 commit (found $COMMIT_COUNT)"
            echo "Please squash your commits: git rebase -i HEAD~$COMMIT_COUNT"
            exit 1
          fi
          
          # Check conventional commit format
          if ! echo "$COMMIT_MSG" | grep -qE "^(build|ci|docs|feat|fix|perf|refactor|style|test|revert)(\([a-z0-9-]+\))?!?: .+"; then
            echo "❌ FAIL: Commit must follow Conventional Commits format"
            echo ""
            echo "Valid examples:"
            echo "  build: Changes that affect the build system or external dependencies"
            echo "  ci: Changes to our CI configuration files and scripts"
            echo "  docs: Documentation only changes"
            echo "  feat: A new feature"
            echo "  fix: A bug fix"
            echo "  perf: A code change that improves performance"
            echo "  refactor: A code change that neither fixes a bug nor adds a feature"
            echo "  style: Changes that do not affect the meaning of the code"
            echo "  test: Adding missing tests or correcting existing tests"
            echo "  revert: (followed by the header of the reverted commit)"
            echo ""
            echo "Your commit: '$COMMIT_MSG'"
            exit 1
          fi
          
          echo "✅ SUCCESS: PR has 1 conventional commit"
