name: Simple Commit Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR has exactly one conventional commit
        run: |
          # Count commits between base and head
          COMMITS=$(git log --oneline ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
          COMMIT_MSG=$(echo "$COMMITS" | head -1)
          
          echo "=== COMMIT VALIDATION ==="
          echo "Commit count: $COMMIT_COUNT"
          echo "Commit message: $COMMIT_MSG"
          echo "========================="
          
          # Check single commit
          if [ "$COMMIT_COUNT" -ne 1 ]; then
            echo "❌ FAIL: PR must have exactly 1 commit (found $COMMIT_COUNT)"
            echo "Please squash your commits: git rebase -i HEAD~$COMMIT_COUNT"
            exit 1
          fi
          
          # Check conventional commit format
          if ! echo "$COMMIT_MSG" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?!?: .+"; then
            echo "❌ FAIL: Commit must follow Conventional Commits format"
            echo ""
            echo "Valid examples:"
            echo "  feat: add user authentication"
            echo "  fix(api): resolve timeout issues" 
            echo "  chore: update dependencies"
            echo "  feat!: remove deprecated API (breaking change)"
            echo ""
            echo "Your commit: '$COMMIT_MSG'"
            exit 1
          fi
          
          echo "✅ SUCCESS: PR has 1 conventional commit"
